import crypto from 'node:crypto';
import { AiProviderName } from '@prisma/client';
import type {
  AiProvider,
  CompletionRequest,
  CompletionResponse,
  EmbeddingRequest,
  EmbeddingResponse,
} from '../types';

/**
 * A provider that needs no API key.
 *
 * This exists so the entire academic loop — generate a task, answer it, get an
 * evaluation — can be demonstrated, tested and developed against with zero
 * spend and no network. It is not a simulation of intelligence: it returns
 * well-formed, obviously synthetic output so nobody can mistake a mock run for
 * a real one.
 */
export class MockProvider implements AiProvider {
  public readonly name = AiProviderName.MOCK;
  public readonly supportsEmbedding = true;

  async complete(request: CompletionRequest): Promise<CompletionResponse> {
    const started = Date.now();
    const prompt = request.messages.map((m) => m.content).join('\n');

    const text = request.json ? this.jsonFor(request, prompt) : this.proseFor(prompt);

    return {
      text,
      provider: this.name,
      model: 'mock-1',
      promptTokens: Math.ceil(prompt.length / 4),
      completionTokens: Math.ceil(text.length / 4),
      latencyMs: Date.now() - started,
    };
  }

  private jsonFor(request: CompletionRequest, prompt: string): string {
    if (request.feature === 'ANSWER_EVALUATION' || request.feature === 'VIVA_EVALUATION') {
      return JSON.stringify({
        score: 6,
        maxScore: 10,
        verdict: 'partially_correct',
        whatWentRight:
          'You identified the right principle and set the problem up correctly.',
        whatWentWrong: 'The final step dropped a factor and the units were not carried through.',
        whyItWentWrong:
          'Substituting numbers before rearranging symbolically makes it easy to lose a term.',
        correctApproach:
          'Rearrange the formula fully in symbols, then substitute once at the end and check the units.',
        improvementTip: 'Write the unit next to every quantity as you go.',
        conceptualErrors: [],
        calculationErrors: ['dropped factor in the final step'],
        missingSteps: ['unit check'],
        confidence: 0.4,
        mockNotice: 'Generated by the mock provider. Configure AI_PROVIDER for real evaluation.',
      });
    }

    if (request.feature === 'TASK_GENERATION') {
      const count = Number(/questionCount"?\s*[:=]\s*(\d+)/.exec(prompt)?.[1] ?? 5);

      return JSON.stringify({
        questions: Array.from({ length: Math.min(count, 10) }, (_, i) => ({
          type: i % 3 === 0 ? 'MCQ_SINGLE' : i % 3 === 1 ? 'NUMERICAL' : 'SHORT_ANSWER',
          difficulty: 'MEDIUM',
          body: `[MOCK] Practice question ${i + 1} generated from the supplied material.`,
          ...(i % 3 === 0
            ? {
                options: [
                  { id: 'a', text: 'First option' },
                  { id: 'b', text: 'Second option' },
                  { id: 'c', text: 'Third option' },
                  { id: 'd', text: 'Fourth option' },
                ],
                correctAnswer: 'b',
              }
            : {}),
          ...(i % 3 === 1 ? { correctAnswer: 42 } : {}),
          ...(i % 3 === 2 ? { modelAnswer: 'A model answer would appear here.' } : {}),
          explanation: 'The mock provider does not reason about the material.',
          marks: 2,
          expectedTimeSec: 120,
          sourceChunkIndexes: [0],
        })),
      });
    }

    return JSON.stringify({ mock: true, note: 'No mock shape defined for this feature.' });
  }

  private proseFor(prompt: string): string {
    return [
      '[MOCK RESPONSE] The AI provider is not configured, so this is placeholder text.',
      '',
      `The request was ${prompt.length} characters long.`,
      'Set AI_PROVIDER and the matching API key to get a real answer.',
    ].join('\n');
  }

  /**
   * Deterministic pseudo-embeddings.
   *
   * Hashing the input means identical text always yields an identical vector
   * and similar text does not, so retrieval plumbing can be exercised
   * end-to-end. The vectors carry no semantic meaning whatsoever, and
   * retrieval quality under the mock provider tells you nothing about real
   * retrieval quality.
   */
  async embed(request: EmbeddingRequest): Promise<EmbeddingResponse> {
    const started = Date.now();
    const dimension = 1536;

    const vectors = request.input.map((text) => {
      const seed = crypto.createHash('sha256').update(text).digest();
      const vector = new Array<number>(dimension);

      for (let i = 0; i < dimension; i += 1) {
        const byte = seed[i % seed.length] ?? 0;
        vector[i] = ((byte / 255) * 2 - 1) * Math.cos(i * 0.017 + byte);
      }

      const norm = Math.sqrt(vector.reduce((sum, v) => sum + v * v, 0)) || 1;
      return vector.map((v) => v / norm);
    });

    return {
      vectors,
      provider: this.name,
      model: 'mock-embed-1',
      totalTokens: request.input.reduce((sum, t) => sum + Math.ceil(t.length / 4), 0),
      latencyMs: Date.now() - started,
    };
  }
}
